import React, { Suspense } from "react";
const Card = React.lazy(() => import("@/components/ui/card").then(m => ({ default: m.Card })));
const Badge = React.lazy(() => import("@/components/ui/badge").then(m => ({ default: m.Badge })));
const Button = React.lazy(() => import("@/components/ui/button").then(m => ({ default: m.Button })));
import {
  LucideCamera,
  LucidePin,
  LucidePlay,
  LucidePlus,
  LucideUsers,
  LucideVideo,
  LucideUndo,
} from "lucide-react";
import { useContent } from "@/hooks/useLocalData";
import { useRef, useState, useEffect, useCallback } from "react";
import type { ContentIdea } from "@/types";
import { analytics } from "@/lib/analytics";
import { aiErrorHandler } from "@/lib/aiErrorHandler";

const platforms = [
  { name: "TikTok", icon: LucideVideo },
  { name: "Instagram", icon: LucideCamera },
  { name: "Facebook", icon: LucideUsers },
  { name: "YouTube Shorts", icon: LucidePlay },
  { name: "Pinterest", icon: LucidePin },
];


function ContentPlanner() {
  // Content state and undo stack
  const [content, setContent] = useContent();

  // Persistent undo/redo stacks
  const [undoStack, setUndoStack] = useState<ContentIdea[][]>(() => {
    if (typeof window !== "undefined") {
      const saved = window.localStorage.getItem("content-undo-stack");
      return saved ? JSON.parse(saved) : [];
    }
    return [];
  });
  const [redoStack, setRedoStack] = useState<ContentIdea[][]>(() => {
    if (typeof window !== "undefined") {
      const saved = window.localStorage.getItem("content-redo-stack");
      return saved ? JSON.parse(saved) : [];
    }
    return [];
  });
  const [canUndo, setCanUndo] = useState(undoStack.length > 0);
  const [canRedo, setCanRedo] = useState(redoStack.length > 0);

  // AI content generation handler (must be after all state declarations)
  const [aiLoading, setAiLoading] = useState(false);
  const [aiError, setAiError] = useState("");
  const handleGenerateAI = async () => {
    analytics.track('generate_ai_content');
    setAiLoading(true);
    setAiError("");
    try {
      const res = await fetch("/api/ai-assistant", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: "Give me a fresh, creative, and actionable content idea for a small business owner to post on social media. Respond with just the idea title." }),
      });
      const data = await res.json();
      if (data.answer) {
        setUndoStack((prev) => [...prev, [...content]]);
        setRedoStack([]);
        setContent([
          {
            id: `content-${Date.now()}`,
            title: data.answer.trim(),
            platform: "TikTok",
            business: "",
            status: "Idea",
            hook: "",
            caption: "",
            hashtags: "",
            postDate: new Date().toISOString().slice(0, 10),
            notes: "Generated by AI",
          },
          ...content,
        ]);
      } else {
        setAiError("AI did not return a valid idea.");
        // AI-powered error handling for empty answer
        const suggestion = await aiErrorHandler.handle("AI did not return a valid idea.", "AI content generation");
        setTimeout(() => setAiError(suggestion), 1000);
      }
    } catch (e) {
      setAiError("Failed to connect to AI.");
      // AI-powered error handling for fetch failure
      const suggestion = await aiErrorHandler.handle(e?.toString?.() || "Unknown error", "AI content generation");
      setTimeout(() => setAiError(suggestion), 1000);
    }
    setAiLoading(false);
  };

  // Debounced auto-save for content
  const debounce = (fn: (...args: any[]) => void, delay: number) => {
    let timer: any;
    return (...args: any[]) => {
      clearTimeout(timer);
      timer = setTimeout(() => fn(...args), delay);
    };
  };
  const saveStacks = useCallback(
    debounce((undo, redo) => {
      window.localStorage.setItem("content-undo-stack", JSON.stringify(undo));
      window.localStorage.setItem("content-redo-stack", JSON.stringify(redo));
    }, 300),
    []
  );

  useEffect(() => {
    setCanUndo(undoStack.length > 0);
    setCanRedo(redoStack.length > 0);
    saveStacks(undoStack, redoStack);
  }, [undoStack, redoStack, saveStacks]);

  // Add Content (demo only)
  const handleAddContent = () => {
    analytics.track('add_content');
    setUndoStack((prev) => [...prev, [...content]]);
    setRedoStack([]);
    setContent([
      {
        id: `content-${Date.now()}`,
        title: "New Content Idea",
        platform: "TikTok",
        business: "",
        status: "Idea",
        hook: "",
        caption: "",
        hashtags: "",
        postDate: new Date().toISOString().slice(0, 10),
        notes: "",
      },
      ...content,
    ]);
  };

  // Undo last change
  const handleUndo = () => {
    if (undoStack.length > 0) {
      if (window.confirm("Undo last change?")) {
        analytics.track('undo_content');
        const prev = undoStack[undoStack.length - 1];
        setUndoStack((stack) => stack.slice(0, -1));
        setRedoStack((stack) => [...stack, [...content]]);
        if (prev) setContent(prev);
      }
    }
  };

  const handleRedo = () => {
    if (redoStack.length > 0) {
      if (window.confirm("Redo last undone change?")) {
        analytics.track('redo_content');
        const next = redoStack[redoStack.length - 1];
        setRedoStack((stack) => stack.slice(0, -1));
        setUndoStack((stack) => [...stack, [...content]]);
        if (next) setContent(next);
      }
    }
  };

  // Keyboard shortcuts for undo/redo
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "z") {
        e.preventDefault();
        handleUndo();
      }
      if ((e.ctrlKey || e.metaKey) && (e.key === "y" || (e.shiftKey && e.key === "z"))) {
        e.preventDefault();
        handleRedo();
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  });

  // Clear all localStorage and reload the page
  const handleClearAllData = () => {
    if (window.confirm('Are you sure you want to clear ALL your data? This cannot be undone.')) {
      window.localStorage.clear();
      window.location.replace(window.location.href);
    }
  };

  // Analytics viewer state
  const [showAnalytics, setShowAnalytics] = useState(false);
  const [analyticsEvents, setAnalyticsEvents] = useState<{ event: string; timestamp: string; props?: any }[]>([]);
  useEffect(() => {
    if (showAnalytics) {
      setAnalyticsEvents(analytics.getEvents());
    }
  }, [showAnalytics]);

  return (
    <Suspense fallback={<div className="text-center py-8">Loading planner...</div>}>
      <div className="max-w-4xl mx-auto px-2 sm:px-4 py-6 sm:py-12 space-y-6 sm:space-y-10">
        <div className="flex flex-col sm:flex-row items-center sm:justify-between gap-2 sm:gap-0 mb-4 sm:mb-8">
          <h2 className="text-2xl sm:text-4xl font-extrabold text-pink drop-shadow-lg tracking-tight">Content Planner</h2>
          <div className="flex gap-2">
            <Button className="bg-pink text-white rounded-full shadow-glass flex items-center gap-2 sm:gap-3 px-4 sm:px-6 py-2 sm:py-3 text-base sm:text-lg font-bold hover:bg-pink-dark transition" onClick={handleAddContent}>
              <LucidePlus className="w-5 sm:w-6 h-5 sm:h-6" /> Add Content
            </Button>
            <Button className="bg-gold text-black rounded-full shadow-glass flex items-center gap-2 px-4 py-2 text-base font-bold disabled:opacity-50" onClick={handleGenerateAI} disabled={aiLoading} title="Generate content idea with AI">
              🤖 Generate with AI
            </Button>
              {aiLoading && <div className="text-pink font-bold mt-2 animate-pulse">AI is brainstorming your next big idea...</div>}
              {aiError && <div className="text-destructive font-bold mt-2">{aiError}</div>}
            <Button className="bg-gold text-black rounded-full shadow-glass flex items-center gap-2 px-4 py-2 text-base font-bold disabled:opacity-50" onClick={handleUndo} disabled={!canUndo} title="Undo last change (Ctrl+Z)">
              <LucideUndo className="w-5 h-5" /> Undo
            </Button>
            <Button className="bg-gold text-black rounded-full shadow-glass flex items-center gap-2 px-4 py-2 text-base font-bold disabled:opacity-50" onClick={handleRedo} disabled={!canRedo} title="Redo last change (Ctrl+Y)">
              <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M21 7v6h-6"/><path d="M3 17a9 9 0 0 1 14-7.7l4 3"/></svg> Redo
            </Button>
            <Button variant="destructive" className="rounded-full px-4 sm:px-6 py-2 sm:py-3 text-base sm:text-lg font-bold" onClick={handleClearAllData}>
              Clear All Data
            </Button>
            <Button className="bg-black text-gold border-gold border-2 rounded-full px-4 py-2 text-base font-bold" onClick={() => setShowAnalytics((v) => !v)}>
              {showAnalytics ? 'Hide Analytics' : 'Show Analytics'}
            </Button>
          </div>
        </div>
        {showAnalytics && (
          <Card className="mb-6 p-4 bg-white/90 border-2 border-gold">
            <div className="font-bold text-pink mb-2">Analytics Events</div>
            {analyticsEvents.length === 0 ? (
              <div className="text-muted-foreground">No events tracked yet.</div>
            ) : (
              <ul className="max-h-48 overflow-y-auto text-xs space-y-1">
                {analyticsEvents.slice().reverse().map((e, i) => (
                  <li key={i} className="border-b border-gold/30 py-1">
                    <span className="font-bold text-black">{e.event}</span> <span className="text-muted-foreground">{e.timestamp}</span>
                  </li>
                ))}
              </ul>
            )}
          </Card>
        )}
        <Card className="p-4 sm:p-8 rounded-4xl shadow-glass border-2 border-gold bg-glass backdrop-blur-2xl hover:scale-[1.01] transition-transform">
          <div className="flex flex-wrap gap-2 sm:gap-3 mb-2 sm:mb-4">
            {platforms.map(({ name, icon: Icon }) => (
              <Badge key={name} className="bg-gold text-black flex items-center gap-1 sm:gap-2 px-3 sm:px-4 py-1 sm:py-2 text-sm sm:text-base font-semibold">
                <Icon className="w-4 sm:w-5 h-4 sm:h-5" /> {name}
              </Badge>
            ))}
          </div>
          <div className="text-sm sm:text-lg text-muted-foreground font-semibold mb-4">Content planning features coming soon...</div>
          <ul className="space-y-2">
            {content.map((c) => (
              <li key={c.id} className="bg-white/80 rounded-lg px-4 py-2 shadow border border-gold text-black font-semibold">
                {c.title} <span className="text-xs text-muted-foreground">({c.platform})</span>
              </li>
            ))}
          </ul>
          <div className="mt-4">
            <div className="font-bold text-pink mb-1">Undo/Redo History</div>
            <div className="flex flex-wrap gap-2 text-xs">
              {undoStack.length > 0 && <span className="bg-gold/60 px-2 py-1 rounded">Undo: {undoStack.length} step(s)</span>}
              {redoStack.length > 0 && <span className="bg-gold/40 px-2 py-1 rounded">Redo: {redoStack.length} step(s)</span>}
              {undoStack.length === 0 && redoStack.length === 0 && <span className="text-muted-foreground">No undo/redo history</span>}
            </div>
          </div>
        </Card>
      </div>
    </Suspense>
  );
}

export default React.memo(ContentPlanner);
